<div class="navbar">
  	<div class="navbar-inner">
  		<ul class="nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Candidacies
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="invitations_to_interview.php">Invitations to Interview</a>
            </li>
            <li>
              <a href="application_sent.php">Application Sent</a>
            </li>
          </ul>
        </li>   
  			<li class="dropdown">
  				<a href="#" class="dropdown-toggle" data-toggle="dropdown">	  					
  					Messages<span class="xalert" id="inbox">0</span>
  				</a>
  				<ul class="dropdown-menu">
  					<li><a href="inbox.php">Inbox</a></li>
  					<li><a href="sent.php">Sent</a></li>
  					<li><a href="archive.php">Archive</a></li>
  				</ul>
  			</li>  			
         <li>
          <a href="contacts.php">Contacts</a>
        </li>
        <li>
          <a href="contracts.php">Contracts</a>
        </li>        
  			<li><a href="logout.php">Logout</a></li>
  		</ul>
		</div>
</div>	